### ISSUE TITLE
ENDER 3 stock LCD NOT working, NO power LED 

### ISSUE THREAD

**Issue by jarjartee** [makerbase-mks/SGEN_L#1]
Just received my Gen L board , flashed firmware in Arduino - all works apart from when connecting to power from 24V PSU - NO LED but fans are going. Tried 2 different tutorials to get LCD working BUT NOGO

**Comment by pattonwebz** [comment]
I had to flip my display ribbon upside down on screen side (and cut the tab so it could go in the wrong way) to get it to work.

**Comment by jarjartee** [comment]
Tried all that , problem is NO power LED when connecting to 24v which indicates a problem 
![6CC5792C-4586-4EAD-9309-47EFF55C8799](https://user-images.githubusercontent.com/1782985/59978825-96fabc80-95d8-11e9-9035-302782a48190.jpeg)
somewhere - USB connection is fine on its own but does NOT WORK whilst hooked up to power.

**Comment by pattonwebz** [comment]
Sorry I misunderstood your issue originally. I don't know anything to help with your current problem sadly :(

**Comment by thisiskeithb** [comment]
The [current pins file](https://github.com/makerbase-mks/SGEN_L/blob/05350a1864cafee9987f52e10155980adfbb508f/Firmware/Marlin-bugfix-2.0.x/Marlin/src/pins/pins_MKS_SGEN_L.h) in this repo is not setup for the Ender-3 display (`CR10_STOCKDISPLAY`), but look for board support in the main Marlin repo soon!

**Comment by jarjartee** [comment]
Patton - YOUR're a STAR - swapping the end stops did the trick - there's life in the display now as well BUT not quite right configured - thanks Keith

**Comment by thisiskeithb** [comment]
Here's a link to the PR in Marlin's repo with Ender-3/`CR10_STOCKDISPLAY` (and several others) support: https://github.com/MarlinFirmware/Marlin/pull/14411

**Comment by pattonwebz** [comment]
Happy to have helped and I am glad you shared that picture so we could figure out what was up :)

**Comment by thisiskeithb** [comment]
@jarjartee: The SGEN-L is now supported upstream in Marlin, so give it a test.

**Comment by pattonwebz** [comment]
@thisiskiethb with the new changes do you think that will mean all of us that flipped our cables will need to flip them back round too? I guess it will bit figured I'd ask if you know since I'm unlikely to do any flashing of an updated marlin anything this week.

**Comment by thisiskeithb** [comment]
You'll have to continue to rotate your cables on MKS boards.

**Comment by pattonwebz** [comment]
Good that I asked then before trying. Keeping cable flipped suits me fine. Thanks for the info :)
