### ISSUE TITLE
Bl touch

### ISSUE THREAD

**Issue by JUJU3D** [makerbase-mks/SGEN_L#10]
Hello any one know how to use bot touch with mks sgenL what IS a good pin,thanks a lot

**Comment by Sharkys80** [comment]
The pins for Bl Touch : 

![Unbenannt](https://user-images.githubusercontent.com/29855640/70228713-19c19f00-1755-11ea-8881-8597ebd6b81d.PNG)

**Comment by crazy72** [comment]
Be careful in case you are upgrading from a stock MKS. Brown is GND and Red 5V. Sharkys80 are you sure you have to conenct the white and black to Z+ ? in the previous board everything is connected to X- , Y- and Z-

**Comment by Sharkys80** [comment]
Correct its Zmin

![grafik](https://user-images.githubusercontent.com/29855640/71337796-5d861800-254d-11ea-927f-ea5896711923.png)

**Comment by CaptainRoot** [comment]
I upgraded my last weekend, i used z-pin without any problems

**Comment by makerbase-mks** [comment]
We has about how to use 3D TOUCH video tutorial, you can refer to：https://www.youtube.com/watch?spm=a2g0o.detail.1000023.1.2b603d9b93YISB&v=4tmdXvN0K4U
