### ISSUE TITLE
I want to use the pt100 thermistor.

### ISSUE THREAD

**Issue by SharePARTS** [makerbase-mks/SGEN_L#13]
Is there a spare analog pin available?

**Comment by borland1** [comment]
Besides TH1, TB (TH2), and TH3 (silkscreened TH2 on PCB), there are two at AUX-1 (RX0, TX0), and one at T1 (pad on board marked T1 P0.26).

**Comment by SharePARTS** [comment]
> AUX-1 (RX0, TX

Please tell me the pin number of TX, RX.

**Comment by borland1** [comment]
TX0 (P0.2 ), Aux-1 pin 6
RX0 (P0.3),  Aux-1 pin 8

**Comment by makerbase-mks** [comment]
![image](https://user-images.githubusercontent.com/12979070/75601417-d9748180-5af5-11ea-8cf9-d394381b464f.png)
You can refer to this picture.
