### ISSUE TITLE
SGEN-L + MKS TMC2130 TMC connection error

### ISSUE THREAD

**Issue by flygja** [makerbase-mks/SGEN_L#18]
Hi I bought a SGEN-L and TMC2130 from MKS for X, Y, Z and E0. I followed the user guide to plug in 4 jumpers on the left side for each driver. I have compiled and uploaded Marlin 2.0-bugfix from MKS github. I can't get the motor drivers to work. The LCD screen shows TMC connection error and when I send M122 I get the error below.

Testing X connection... Error: All HIGH
Testing Y connection... Error: All HIGH
Testing Z connection... Error: All HIGH
Testing E connection... Error: All HIGH

Temp reading, endstop switches, hotend/bed heater are working. Any idea what could be the issue?

**Comment by mks-viva** [comment]
Hi, please provide your firmware and motherboard wiring diagram.

**Comment by flygja** [comment]
I managed to get it working with Marlin 2.0.4.4. Have to enable "TMC_USE_SW_SPI" in configuration_adv.h. Please add that into the user manual as well. Thanks

**Comment by mks-viva** [comment]
OK. It seems pretty good.

**Comment by Crazor** [comment]
I've got the same issue. No matter if I'm enabling TMC_USE_SW_SPI or not, M122 says All HIGH. I've got TMC2130 modules from MKS. Do I need to do anything special except setting the four green jumpers under each driver and the 3.3V jumper?

**Comment by mks-viva** [comment]
You need connect 12-24V power

**Comment by Crazor** [comment]
Of course I have 12V hooked up, just didn't mention it.

**Comment by mks-viva** [comment]
You need power on it of Dc12-24V

**Comment by Crazor** [comment]
As I stated, I have 12V hooked up as well.

**Comment by mks-viva** [comment]
Can you provide your wiring and your firmware to me, and i will test it, but it may be tomorrow, because for me, it is night.

**Comment by Crazor** [comment]
On the bottom side of each driver board, there are two 0 ohm jumpers labeled CFG5 and CFG4. CFG5 (the one on top) is soldered on the left pad, CFG4 (the one near the edge of the board) is soldered on the right side. Is that correct for SPI mode?

**Comment by mks-viva** [comment]
I want to know, where did you buy your TMC2130, because I know that MKS does not currently sell TMC2130 drivers.

**Comment by Crazor** [comment]
I bought them about a year ago off of MKS's AliExpress store, IIRC. I didn't use them until now.

**Comment by mks-viva** [comment]
Okay, then, I want to tell you that MKS TMC2130 is in SPI mode by default, you can use it directly by plugging it into the motherboard.

**Comment by mks-viva** [comment]
Can you provide your firmware to me?

**Comment by Crazor** [comment]
[The complete firmware tree I use](https://github.com/Crazor/Marlin/tree/2.0.x-MKS-SGEN_L)

The relevant config files:
[Configuration.h](https://github.com/Crazor/Marlin/blob/2.0.x-MKS-SGEN_L/Marlin/Configuration.h)
[Configuration_adv.h](https://github.com/Crazor/Marlin/blob/2.0.x-MKS-SGEN_L/Marlin/Configuration_adv.h)

**Comment by mks-viva** [comment]
Ok! I will test it, but it may be tomorrow.

**Comment by Crazor** [comment]
Nevermind, I got this working now. It was a combination of bad software settings and a bad driver module. Got 4 out of 5 working, must have fried the fifth one...

For anyone wondering: Put in four jumpers in the green position below every TMC2130 driver module, put the drive IC power jumper (below the Z driver module) on 3.3V.

As for software: 
Define X_DRIVER_TYPE  TMC2130 (and any other axis you want to use) in Configuration.h, define TMC_USE_SW_SPI in Configuration_adv.h (but none of the pins below that line, they are defined correctly with the board's pins), and define TMC_DEBUG if you want to look at the driver's registers with M122.

**Comment by mks-viva** [comment]
It is will working, it is perfect. So, i will close this issues.
