### ISSUE TITLE
Mks board in wanhao duplicator 5s mini NO firmware

### ISSUE THREAD

**Issue by christoels** [makerbase-mks/SGEN_L#20]
Hi i cant find the firmware for this setup anywhere have a mks 1.0 controller board in my wanhao duplicator 5s mini printer. With the 3.2 tft screen. I dont know much about firmware and have been trying for a week now to get printer to work. Can anyone please please assist would like to use my printer

**Comment by mks-viva** [comment]
Hi! Generally, if you use marlin firmware, you only need to set general options in the configuration.h file, and other parameters do not need to be modified.
