### ISSUE TITLE
LCD for SGEN_L

### ISSUE THREAD

**Issue by elcatedratico** [makerbase-mks/SGEN_L#22]
Hello, i just bought my first MKS Board (SGEN L). I hooked up the MKS TFT32 and it worked instantly. Now, I also want to add a LCD Display to see, how long it takes to upgrade the firmware and if it succeeded and maybe get some informations from the board (Maybe for PID tuning). I do have an old lcd2004 5button but I don't know, how to connect it to EXP1.

Is there another LCD which is more plug and play? (Using Marlin 2.0.x)

Cheers, Andy

**Comment by mks-viva** [comment]
Hi! The LCD screen is directly connected to the EXP1, EXP2 interface
