### ISSUE TITLE
TMC2209 Bi-Directional UART Master/Slave Address Configuration, Marlin 2.0 

### ISSUE THREAD

**Issue by borland1** [makerbase-mks/SGEN_L#26]
When using MKS TMC2209 driver modules, it is not clear how to set up MKS_SGEN_L board jumpers for optional bi-directional PDN_UART addressing with MS1 and MS2 ( MS1_ADDR0 and MS2_ADDR1 ) jumpers.

Marlin 2.0 provides ability to setup addressing ( 0 thru 3) for up to four TMC2209 stepper drivers in Configuration_adv.h file, in section 'tmc_smart'...   In comments, the Address Table is shown as:

` * Address | MS1  | MS2
  *       0 | LOW  | LOW
  *       1 | HIGH | LOW
  *       2 | LOW  | HIGH
  *       3 | HIGH | HIGH`

followed by the defines  assigning specific address values, as appropriate:

#define  X_SLAVE_ADDRESS 0
#define  Y_SLAVE_ADDRESS 0
#define  Z_SLAVE_ADDRESS 0
#define E0_SLAVE_ADDRESS 0

The MKS_SGEN_L schematic shows:
- MS1 is pulled low to ground through resistor Rm1.  Resistor Rm1 for MS1 does not appear to exist when looking at the PCB silkscreen.  I think this is a mistake on the diagram, because....
- EN pin is pulled high to VDD through 10K ohm resistor Rm1.  Resistor Rm1 for EN is identified on PCB board silkscreen. TMC2209 driver is disabled until EN pin is pulled low by the board's processor.

**Comment by NeoMod** [comment]
@borland1 did you managed to solve the issue?

**Comment by borland1** [comment]
> @borland1 did you managed to solve the issue?

Yes.  What I missed is on the schematic, the motor driver slots are shown as typical (only one shown) with label "UART", however there is actually UART1 (E0), UART2 (X), UART3 (Y), UART4 (Z), and UART5 (E1).
So, each TMC driver has it's own separate UART line and so all installed TMC drivers can use same addresses set by driver pins MS1 and MS2.  No address conflicts will be present.
I only installed two TMC2209 drivers for X and Y.
