### ISSUE TITLE
PWM Pins for RGB Led Strip

### ISSUE THREAD

**Issue by Bubolz** [makerbase-mks/SGEN_L#32]
I need to implement LED lighting using an analog RGB LED module,  but only has 2 pins with free PWM for servos ... what other PWM-capable pins could I use?

Thanks!

**Comment by makerbase-mks** [comment]
Hi! I want to know, do you use EXP1?

**Comment by Bubolz** [comment]
Yes I will use LCD MKS Min, but I will only use one hotend. Could I use the two servo pins (P1.23 and P2.0) and the HE1 pin (P2.6)?

**Comment by makerbase-mks** [comment]
of course! Yes you can use it.

**Comment by Bubolz** [comment]
Is there any more PWM pins on the limit switches that can be used? maybe in X +?

**Comment by makerbase-mks** [comment]
No, because limit switch has pullup resistor, but you can use LED1-LED4 pin
![image](https://user-images.githubusercontent.com/12979070/91921313-c5584980-ecfd-11ea-99eb-da626d5890ec.png)
![image](https://user-images.githubusercontent.com/12979070/91921271-a9ed3e80-ecfd-11ea-95fd-0e81fbd92481.png)

**Comment by Bubolz** [comment]
Right! Thanks for the quick response.

I need a pwm that already has a pin for connection. On some machines I’ll use touch LCDs so I’ll have EXP1 and EXP2 free,   previously you suggested using EXP,  what are the available pins?

![EXP](https://user-images.githubusercontent.com/25917958/91994287-d492c380-ed0c-11ea-9d1b-a0645a9a11b8.png)

**Comment by makerbase-mks** [comment]
![image](https://user-images.githubusercontent.com/12979070/92060196-b937bf00-edc5-11ea-8887-c8bfd40cafdd.png)
You can use P3.25 or P3.26
