### ISSUE TITLE
Future request: USB 3.0 Support

### ISSUE THREAD

**Issue by biocrypto730** [makerbase-mks/SGEN_L#6]
For next generation, (SGEN_L_2), please consider adding USB 3.0 support.

It will make it faster when sending 32-bit numbers over serial. It will allow you to use USB 3.0 webcams on same USB 3.0 controller. Less glitches, more stability. USB 3.0 is more simple than ethernet.

**Comment by Ccleorina87** [comment]
NXP1768 have only USB 2.0 full-speed device/Host/OTG controller build-in... even STM32F407ZG Is limited to USB 2.0...
