### ISSUE TITLE
Print from SDcard on boot

### ISSUE THREAD

**Issue by mrhempman69** [makerbase-mks/SGEN_L#8]
Is it possible to print from the SD card on boot using these boards? For example, once connecting a 12V power supply, the board should power on, and the firmware should read a file from the SD card and begin printing that.

Normally, marlin firmware uses a file called `autostart.g` from the SD card and prints from that on boot.  But when I include that file in the root of my SDcard, the SGEN_L doesn't start printing from it when power is supplied.

Is the SD card only used for firmware flashing? 

Is there any way to print from this board without using a USB connection? 

Possibly related: https://github.com/makerbase-mks/SGEN_L/issues/7

**Comment by makerbase-mks** [comment]
1. It is very certain to tell you that SD is supported for automatic printing;
2.gocde file name must be auto0.g instead of autostart.g
3. You re-edit the gcode file name to try, good luck!

**Comment by biocrypto730** [comment]
Thanks. In my own custom firmware, I did not have `#define SDSUPPORT`. But this firmware does have sd support enabled by default. I thought it was a problem with the board.

**Comment by mrhempman69** [comment]
Thanks. In my own custom firmware, I did not have #define SDSUPPORT. But this firmware does have sd support enabled by default. I thought it was a problem with the board.
